### PR TITLE
support esp32 chips too

### PR DESCRIPTION
**Pull request by nexus166**
small change makes this work on my tinypico boards (specifically m5stickc-plus with buzzer on pin 2)

### CODE REVIEW

**Comment by fruch** [comment]
@nexus166, any change you are telling a bit what are you doing with the esp32 ?

**Comment by nexus166** [comment]
@fruch for now I'm still trying to make every hardware component of the StickC/StickC-Plus work decently within my own custom-built firmware images with MicroPython sources and ESP-IDF downloaded from the actual providers. I'm going to publish a docker based build system soon, in case you're interested.

**Comment by fruch** [comment]
> @fruch for now I'm still trying to make every hardware component of the StickC/StickC-Plus work decently within my own custom-built firmware images with MicroPython sources and ESP-IDF downloaded from the actual providers. I'm going to publish a docker based build system soon, in case you're interested.

sounds interesting...

**Comment by nexus166** [comment]
@fruch I just published my [docker build environment ](https://github.com/nexus166/micropython-esp) that can be used to easily inject py modules and C drivers/apps in the micropython firmware. You also might be interested in this https://github.com/nexus166/st77xx_mpy, it is a fork of st7789 driver adapted to function decently with st7735 too, the result is a much faster experience with the stickc/stickcplus displays compared with the python modules I was able to find

**Pull request merged**
